"""Add back_populates

Revision ID: 0b397f4638ab
Revises: 06612ca9dd9e
Create Date: 2024-05-20 16:04:51.665237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b397f4638ab'
down_revision = '06612ca9dd9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
